site_name: MtnMe.sh
site_author: MtnMe.sh
site_description: "Mountain Mesh: Serving Meshtastic to the Appalachian Mountains (North GA / East TN)"
copyright: © Creative Commons Attribution-ShareAlike 4.0 International License
site_url: https://mtnme.sh/
repo_url: https://github.com/MtnMesh/mtnmesh.github.io
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - About: about.md
  - Guides:
    - Config: config.md
    - Filters: guides/filters.md
  - Devices: devices.md
  - Resources: resources.md
  - Neighbors: neighbors.md

plugins:
  - search
  - social
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
  - git-committers:
      repository: MtnMesh/mtnmesh.github.io
      branch: main

markdown_extensions:
  - toc
  - attr_list
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  favicon: static/favicon.png
  icon:
    logo: fontawesome/solid/mountain
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.action.view
    - content.action.edit

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/4WN32RHGSs
    - icon: fontawesome/brands/github 
      link: https://github.com/mtnmesh
