name: Validate mkdocs upon PR

on:
  # Runs on PRs targeting the default branch
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1 # Shallow fetch during validations, breaks mkdocs-git-revision-date-localized-plugin

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - run: pip install -r requirements.txt

      - run: mkdocs build --verbose
